Feature/geografisk tilknytning bolk
navikt/testnorge pull request #2295
Opened 2022-04-25 12:41 UTC by stigus

2022-04-25 12:50 UTC, krharum approved these changes
Blir bra dette! 😄

2022-04-25 12:50 UTC, krharum commented on apps/dolly-backend/src/main/java/no/nav/dolly/domain/PdlPersonBolk.java
> +        private List<Identinformasjon> identer;
Her har du både ident og identer ved siden av hverandre, er det riktig?

2022-04-25 12:50 UTC, krharum commented on apps/dolly-backend/src/main/resources/pdlperson/pdl-api-schema.graphql
>      STRENGT_FORTROLIG
Har denne også et tredje valg som heter STRENGT_FORTROLIG_UTLAND ?

2022-04-26 06:25 UTC, H153910 requested changes
Feil i visning av testnorge-identer, se gruppe 143, ident 06884399554 (se console melding)

2022-04-26 07:08 UTC, stigus commented on apps/dolly-backend/src/main/java/no/nav/dolly/domain/PdlPersonBolk.java
> +        private List<Identinformasjon> identer;
Ja bolk returnerer FNR/DNR som ident og en liste med AktoerID og FNR osv som identer 👍

2022-04-26 07:09 UTC, stigus commented on apps/dolly-backend/src/main/resources/pdlperson/pdl-api-schema.graphql
>      STRENGT_FORTROLIG
Bra sett, jeg tror denne er autogenerert, kan hende den ikke er helt oppdatert - skal ta en titt 👍

2022-04-26 07:23 UTC, H153910 approved these changes
Ser flott ut :)

2022-04-26 07:31 UTC, merged