Testnorge skd/justering
navikt/testnorge pull request #283
Opened 2020-10-13 13:03 UTC by baardkrk

La til kommandoer for å koble SyntetiseringService vekk fra gamle HodejegerenConsumer.
Innvandringsmeldinger blir nå sendt til TPS som Tilgang Tildelingskode 2 (5212) for å kunne skille mellom identer som har blitt opprettet fra orkestratoren vs. kommer med vanlige innvandringsmeldinger fra dolly.
Det er ikke lenger lov til å ha flere enn 33 relasjoner når man velger far for barn.

2020-10-14 06:19 UTC, krharum commented on apps/testnorge-skd/skd-core/src/main/java/no/nav/registre/skd/consumer/HodejegerenConsumerSkd.java
> +                                .maxInMemorySize(16 * 1024 * 1024))
16 * 1024 * 1024 kan vel defineres som en private static final? Hva er hensikten med denne?

2020-10-14 06:19 UTC, krharum commented on apps/testnorge-skd/skd-core/src/main/java/no/nav/registre/skd/provider/rs/SyntetiseringController.java
> +            "\tVed bestilling av endringskode 0211, genereres tilhørende endringsmelding 3510. Endringskode 0211 blir nå byttet ut med 5212 i stedet.\n\n" +
En forskjell på 0211 og 5212 er at eksisterende barn må umiddelbart etterfølges i trans 2 (barnetrans) record. Ved 0211 har man ikke denne begrensning. Forøvrig, fødselsmelding er som før.

2020-10-14 06:37 UTC, ingvildstoen approved these changes

2020-10-14 06:42 UTC, stigus approved these changes
Ser supert ut 👍

2021-02-02 07:46 UTC, langvatn requested changes
Må bare legge inn en kommentar slik at slack ikke lengere sender meg melding vær dag

2021-10-05 13:20 UTC, closed without merging